version: '3.9'

services:
  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy

  backend:
    build: ./bloglist-backend/
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - MONGODB_URL
      - PORT
      - SECRET
    container_name: backend

  mongo:
    image: mongo
    ports:
      - 3456:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - ./bloglist-backend/mongo_data:/data/db
    container_name: mongo

  frontend:
    build: ./bloglist-frontend/
    ports:
      - 3001:80
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    container_name: frontend